version: '3.8'

services:
  avito-shop-service:
    build: .
    container_name: merch-store
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5431
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: shop

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      # "./migrations/init.sql" - путь к миграциям БД
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

#  test_db:
#    image: postgres:13
#    container_name: postgres_test
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: test
#    volumes:
#      # "./migrations/init.sql" - путь к миграциям БД
#      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - "5430:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'" ]
#      interval: 5s
#      timeout: 10s
#      retries: 5
#      start_period: 10s
networks:
  internal: